---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```
```{r}
dtObject
```

```{r}
typeof(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime
```
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```

```{r}
typeof(twDateTime)
```

```{r}
as.double(twDateTime)
```

```{r}
as.double(LisbonDateTime)
```

```{r}
as.integer(twDateTime)

```

```{r}
a<-1
b<-100
```
```{r}
a+b
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```
```{r}
a+b
```
```{r}
a+bL
class(a+bL)
class(a+b)
```
```{r}
twDateTime1<- ymd("2019-08-11")
twDateTime2 <- ymd("2000-02-01")
twDateTime1-twDateTime2
```
```{r}
class(twDateTime1-twDateTime2)
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```
```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
```{r}
x1 <- 5
y1<- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x3 <- c("小明","小花")
y3 <- c("小明","小華")

```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)
x4 %in% y4
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5

```

```{r}
install.packages("stringr")
```
```{r}
library(stringr)
```

Subset(子集)
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_subset(course,"經濟學")
str_detect(course,"經濟學")
```

Join(合併)
*str_c的c是指concatenate(連鎖)
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
```
```{r}
str_c(month,day)

```

```{r}
str_c(month,"月",day,"日")
```



Split(分割)
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

Replace(取代)
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_replace(dates,"-","月")
```
```{r}
dates <- c("2019-3-11", "2019-4-5",  "2019-2-7")
str_replace_all(dates,"-","/")
```


應用(合併網址)
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("http://github.com/",username,"/",reponame)
```

應用(生日日期改寫)
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
birthday

```
```{r}
year<-str_sub(birthday,1,4)
month<-str_sub(birthday,5,6)
day<-str_sub(birthday,7,8)
str_c("西元",year,"年",month,"月",day,"日")
```

應用(把民國年改寫成西元年)
```{r}
民國年月<-c("099/01","099/02","099/03")
y<- str_sub(民國年月,2,3)
m<- str_sub(民國年月,5,6)
y2<- as.integer(y)
m2<- as.integer(m)
str_c("西元",y2+1911,"年",m2,"月")
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][["三年級"]]
```
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5),  
  blueBox=c(TRUE,FALSE,TRUE,TRUE) 
)
```
```{r}
list(
  greenBox=c("paper","scissor"),
  redBox=c(1,3,2.5)
)
plasticContainer

extract1 <- plasticContainer[c("greenBox")]
extract1[[1]][[1]]
extract2 <- plasticContainer[[c("greenBox")]]
extract2[[1]]
```

```{r}
a <- matrix(c(1:6), nrow=3, ncol=2)
a
```

```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```
```{r}
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m)
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```
```{r}
chosenLETTERS <- LETTERS[1:15]
chosenLETTERS
chosenletters <- letters[1:15]
chosenletters
```
```{r}
matObj1 <-matrix(chosenLETTERS,5,3)
matObj1 
matObj11 <-matrix(chosenLETTERS,3,5)
matObj11
```
```{r}
matObj12 <- matObj1[c(T,F,F,F,T),c(F,T,T)]
matObj12
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
dim(classSurvey)
classSurvey[c(1:60),c(4,5)]
classSurvey[,c(4,5)]
```
``
```{r}
LETTERS 
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
matObj1
```
```{r}
colnames(matObj1)
rownames(matObj1)
```
```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3')
colnames(matObj1)
matObj1
```
```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b[[3]] <- FALSE
b[[5]] <- 7
b
```
```{r}
b[c(3,5)] <- c("False","7")
b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間) 

isAsiaCrisis <- exData3$期間 >= ymd(1997-06-01) & exData3$期間 <= ymd(1998-12-01)
```
```{r}
time1 <- ymd("1997-06-01")
time1
time2 <- ymd("1998-12-01")
time2
isAsiaCrisis <- exData3[[1]] <= time2 & exData3[[1]] >= time1
class(isAsiaCrisis)
isAsiaCrisis
```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
GPA
```
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  sum(transcriptDataFinal$學期成績[logiChosenStudent]*
    transcriptDataFinal$學分數[logiChosenStudent])/
    sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
  return(GPA)
}

```
```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```
```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```
```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```
```{r}
(invoiceList$訂單時區 == "America/New_York") -> nyLogical
(invoiceList$訂單時區 == "Asia/Taipei") -> tpLogical

invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

library(lubridate)
ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],
        tz="America/New_York") -> nyDateTime

invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")

ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],
        tz="Asia/Taipei") -> tpDateTime

invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```

```{r}
library(lubridate)
ymd_hms("1973-02-21 12:05:22", tz="America/New_York") -> fromDateTime
with_tz(fromDateTime,tzone="Asia/Taipei") -> toDateTime
toDateTime
```
```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  time1 <- ymd_hms(input,tz=fromTzone)
  answer <- with_tz(time1,tzone = toTzone)
  return(answer)
}
ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```
```{r}
date_convert_twYM <- function(twDates,dd="01"){
  yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twDates,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  yyyymmdd
}
```
```{r}
textbookURL<-function(){
browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#section-8.1")}
textbookURL()
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs <- a+b*P
  Qd <- c-d*P
  es <- Qs -Qd
  return(list(
    供給量=Qs,
    需求量=Qd,
    超額供給量=es
  )
  )
}
```
```{r}
demand_supply_fun(1,2,3,4,5)
```
```{r}
gpa_fun <- function(studentID){

  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent

    subSample <- transcriptDataFinal[logiChosenStudent,]

    sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
    return(GPA)
  }else{
    message("查無此學號")

 }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號

```
```{r}
fizzbuzz <- function(number){
  if(number %% 15== 0){
    return("fizzbuzz")}
    else if(number%% 3 ==0){
      return("fizz")
    }else if (number%% 5 == 0){
      return("buzz")
    }else {
      return(number)
    }
}
fizzbuzz(27)
fizzbuzz(36)
```












  












